kafka_version: "3.7.2"
scala_version: "2.13"
kafka_tgz_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"

install_dir: /opt
kafka_dir: "{{ install_dir }}/kafka_{{ scala_version }}-{{ kafka_version }}"
kafka_symlink: /opt/kafka
data_root: /var/lib

zookeeper_data_dir: "{{ data_root }}/zookeeper/data"
zookeeper_log_dir: "{{ data_root }}/zookeeper/log"

kafka_data_dir: "{{ data_root }}/kafka/data"
kafka_log_dir: "{{ data_root }}/kafka/log"

certs_dir: /etc/kafka/certs
ca_key_path: "{{ certs_dir }}/ca-key.pem"
ca_crt_path: "{{ certs_dir }}/ca.crt"
cert_valid_days: 825

kafka_plain_port: 9092
kafka_tls_port: 9093

zookeeper_client_port: 2181
zookeeper_quorum_port: 2888
zookeeper_election_port: 3888

sysctl_settings:
  net.core.somaxconn: 1024
  net.ipv4.tcp_fin_timeout: 30
  vm.swappiness: 1
  fs.file-max: 1000000

nofile_limit: 1000000
nproc_limit: 65536

firewalld_zookeeper_ports:
  - "{{ zookeeper_client_port }}/tcp"
  - "{{ zookeeper_quorum_port }}/tcp"
  - "{{ zookeeper_election_port }}/tcp"

firewalld_kafka_ports:
  - "{{ kafka_tls_port }}/tcp"
  - "{{ kafka_plain_port }}/tcp"

selinux_state: enforcing

java_package: "java-17-openjdk-headless"
